name: mais_saude_app
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  carousel_slider: ^4.1.1
  provider: ^6.0.3
  google_fonts: ^3.0.1
  fluttertoast: ^8.0.9
  image_picker: ^0.8.5+3
  hive: ^2.2.2
  hive_flutter: ^1.1.0
  image_picker_web: ^2.1.1
  path_provider: ^2.0.11

  firebase_core: ^1.17.1
  firebase_auth: ^3.3.19
  cloud_firestore: ^3.1.17
  firebase_storage: ^10.2.18

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/