// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCf3EQvn8vb29ML6ISTGieJ2I4_tysCNcQ',
    appId: '1:683815836641:web:dbd20ceb59d7fdf6e290a0',
    messagingSenderId: '683815836641',
    projectId: 'maissaude-343bf',
    authDomain: 'maissaude-343bf.firebaseapp.com',
    storageBucket: 'maissaude-343bf.appspot.com',
    measurementId: 'G-X7PFWTG652',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_GHGCKa8XAPRK9xJeqWxbZYwKshUVxG8',
    appId: '1:683815836641:android:fce26e82f96e2860e290a0',
    messagingSenderId: '683815836641',
    projectId: 'maissaude-343bf',
    storageBucket: 'maissaude-343bf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnOx1VcEESPanBub4CAbMzmQGeGDm3BmU',
    appId: '1:683815836641:ios:aedaa129e6804623e290a0',
    messagingSenderId: '683815836641',
    projectId: 'maissaude-343bf',
    storageBucket: 'maissaude-343bf.appspot.com',
    iosClientId: '683815836641-pap2dmq45p52f3cl1t4sq6hp3517tv4l.apps.googleusercontent.com',
    iosBundleId: 'com.OpenCode.maisSaudeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnOx1VcEESPanBub4CAbMzmQGeGDm3BmU',
    appId: '1:683815836641:ios:aedaa129e6804623e290a0',
    messagingSenderId: '683815836641',
    projectId: 'maissaude-343bf',
    storageBucket: 'maissaude-343bf.appspot.com',
    iosClientId: '683815836641-pap2dmq45p52f3cl1t4sq6hp3517tv4l.apps.googleusercontent.com',
    iosBundleId: 'com.OpenCode.maisSaudeApp',
  );
}
